---
# tasks file for nginx role

- name: Installing apache2
  package:
    name: apache2
    update_cache: yes
    state: present

- name: Adding customized content
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache
